### ISSUE TITLE
Guide me what is usage (difference) of wifi server and wifi client in deauther wi-pwn ?

### ISSUE THREAD

**Issue by igsfm** [samdenty/Wi-PWN#101]
![2020-02-05_193930](https://user-images.githubusercontent.com/60702905/73851987-3e6aed80-4850-11ea-9218-1fe4e9f43e93.png)

**Comment by StijnSimons** [comment]
WiFi server -> own access point
WiFi client -> connect to access point

**Comment by Alpha-1729** [comment]
what is the need of connecting to an accessing point.

**Comment by osysltd** [comment]
brains
