### ISSUE TITLE
captive portal not working

### ISSUE THREAD

**Issue by Alpha-1729** [samdenty/Wi-PWN#102]
how to use the captive portal.

**Comment by osysltd** [comment]
https://github.com/samdenty/Wi-PWN/blob/2fd4adbb65911bec7b2e199d184f92482d3d770d/arduino/Wi-PWN/Wi-PWN.ino#L38

**Comment by Alpha-1729** [comment]
osysltd, i have done that step. after that no network is automatically redirecting to 192.168.4.1.

**Comment by osysltd** [comment]
` Wi-PWN page is available on /wipwn, passwords are accessed using /wipwn.log */ `
