### ISSUE TITLE
как пользоваться PWN

### ISSUE THREAD

**Issue by ales197311** [samdenty/Wi-PWN#115]
Есть где нибудь на русском или на английском инструкция пользователя?

**Comment by osysltd** [comment]
https://github.com/samdenty/Wi-PWN#how-to-use

**Comment by ales197311** [comment]
спасибо ))

**Comment by ales197311** [comment]
прошу прощения. У меня стоит esp 8266 версия 3.0.2. Как установить версию 2.0.0? 
И что означают deauth, beacon, random, probe-request, как ими пользоваться? Где почитать?
