### ISSUE TITLE
Wi-PWN not work on PUYA flash chip

### ISSUE THREAD

**Issue by renat2985** [samdenty/Wi-PWN#81]
It appears that the PUYA flash chip is being adopted by a growing number of manufacturers of the esp8266 modules. My most recent purchases of esp-12 modules from 3 separate suppliers have all had the PUYA chip on-board (for a total of 30 modules). The issue is that Arduino IDE x.xx sketches using any 8266 core can not currently write to SPIFFS on modules with this chip.

Any ideas?

**Comment by StijnSimons** [comment]
You're forced to use the old library so don't think this is possible.
Either update the library and fix the SDK or just use a normal ESP8266
