### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by 29G** [samdenty/Wi-PWN#85]
Has this project been abandoned? I certainly hope not as it's so good compared to spacehunh's castrated firmware that does not allow pressing the FLASH button once to deauth all surrounding networks.

**Comment by samdenty** [comment]
Project does everything that I wanted it to do when I forked it. I'm cool with someone else picking it up + adding features, but otherwise I have other open source that I want to work on.

**Comment by samdenty** [comment]
It's possible that I may bring in deauthing ability to the current project I'm working on [samdenty/zomesp](https://github.com/samdenty/zombesp)
