### ISSUE TITLE
resetting the Deauther wifi ID and password

### ISSUE THREAD

**Issue by forestkunt** [samdenty/Wi-PWN#89]
A friend of mine purchased one of your deauther chips and in true noob fashion changed the settings, wfi id and password then totally forgot all of them. Can you help me out with a root password or something so i can get him off my back to fix this for him. Here is a photo of the chip
![20190309_001837](https://user-images.githubusercontent.com/44524679/54068473-fc7d9580-4201-11e9-9d39-2050878b6933.jpg)

cheers

**Comment by StijnSimons** [comment]
These chips aren't ours. Either way, if you connect it to your PC using a microUSB cable, you can see the password and ssid in the serial console.

**Comment by eastcoastboys** [comment]
@StijnSimons How do we use the serial console to look at the SSID and password
