### ISSUE TITLE
Features request

### ISSUE THREAD

**Issue by osysltd** [samdenty/Wi-PWN#92]
Hi! Thanks for the efficient work, very much appreciated.
I would like to ask for a feature request:
1. captive portal to implement evil twin attack and catch wifi password (like your router firmware needs to be upgraded etc) while deauthing original network ref: https://github.com/taner1/esp8266_deauther
2. deauth hidden WiFi when you know *SSID

**Comment by StijnSimons** [comment]
#86 and #87

**Comment by osysltd** [comment]
@StijnSimons Thanks, checking!

**Comment by lucki1000** [comment]
is this feature already implanted?

**Comment by osysltd** [comment]
https://github.com/samdenty/Wi-PWN/commit/2fd4adbb65911bec7b2e199d184f92482d3d770d
