### ISSUE TITLE
clientScanTime is short

### ISSUE THREAD

**Issue by 971106029** [samdenty/Wi-PWN#99]
#### here is my code :

---------------------------------------------------------------

(''')
#include "LED.h"
#include "JSON.h"
#include "WEB.h"
#include "SerialCommunication.h"
#include "WIFI.h"

#include "webfiles.h" //https://github.com/spacehuhn/esp8266_deauther/tree/master/utils/web_converter
#include "WebInterface.h"

void sniffer(uint8_t *buf, uint16_t len) {
  clientScan.packetSniffer(buf, len);
}

void setup() {
  Serial.begin(9600);
  Serial.println("45555555555555555555555555555555555555555555555555544");
  FastLED.addLeds<NEOPIXEL, DATA_PIN>(leds, NUM_LEDS);
  fill_solid(leds, NUM_LEDS, CRGB::White);
  LED_STATE(LED_CONNECT);
  ConfigWifi(); //建立"HackCUBESpecial_XXXXXX"热点

  
  delay(100);
  EEPROM.begin(4096);
  EEPROM.write(1094, 15);
  delay(100);
  EEPROM.commit();
  delay(100);
  
  wifi_set_promiscuous_rx_cb(sniffer);

  //ConnectWif();
  delay(100);
  LED_STATE(LED_RUN);
  SPIFFS.begin();
  //Serial.swap(); 
  delay(100);
  //WebFileSetup(); 
  WebInterface(); 
  server.begin(); 

(''')

--------------------------------------------------------------------

*************
## Serial debugging information

![image](https://user-images.githubusercontent.com/32324747/67278534-bd375700-f4fb-11e9-8294-7dfa28e7f9db.png)

**Comment by StijnSimons** [comment]
What does this have to do with Wi-PWN?

**Comment by 971106029** [comment]
> 这与Wi-PWN有什么关系？

Hello, I mean. This problem occurred when I ported this project to my project. But I can't find the problem. So I want you to help me find it. Thank you.

**Comment by osysltd** [comment]
Closing as not relevant to the repo
